service: 'stack-coffee-talk-cls'

provider:
  name: aws
  stage: ${opt:env, 'dev'}
  runtime: nodejs8.10
  region: 'eu-west-1'
  environment:
    S3_BUCKET_NAME: serverless-stack-labs-coffee-talk-cls
  variableSyntax: "\\${((?=self:|env:|opt:|ssm:|s3:|cf:|deep:|file\\()[ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}"

package:
  exclude:
    - "**/*"
  include:
    - templates/lambdas/getPosts.js
    - templates/lambdas/translator.js

functions:
  ${file(./templates/api.yml)}

resources:
  - ${file(./templates/static-website.yml)}
  - ${file(./templates/iam.yml)}